alg = input("Digite algo: ")
print(f'O tipo primitivo desse valor é {type(alg)}')
print(f'Só tem espaços? {alg.isspace()}')
print(f'É um número? {alg.isnumeric()}')
print(f'É alfabético? {alg.isalpha()}')
print(f'É alfanumérico: {alg.isalnum()}')
print(f'Está todo em maiúsculas? {alg.isupper()}')
print(f'Está todo em minúsculas? {alg.islower()}')
print(f'Está capitalizada? {alg.istitle()}')
